"""add boss and boss_fight tables, combat_role and is_default to stat

Revision ID: 8459fa99761b
Revises: c6058206f258
Create Date: 2026-07-08 15:47:26.575203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8459fa99761b'
down_revision: Union[str, Sequence[str], None] = 'c6058206f258'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boss_fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fight_date', sa.Date(), nullable=False),
    sa.Column('boss_hp', sa.Integer(), nullable=False),
    sa.Column('damage_dealt', sa.Integer(), nullable=False),
    sa.Column('boss_level_at_time', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bosses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('pending_failures', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )

    combat_role_enum = postgresql.ENUM('health', 'strength', 'agility', 'focus', 'intellect', name='combatrole')
    combat_role_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('stats', sa.Column('combat_role', sa.Enum('health', 'strength', 'agility', 'focus', 'intellect', name='combatrole'), nullable=True))
    op.add_column('stats', sa.Column('is_default', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('current_hp', sa.Integer(), nullable=False, server_default='100'))
    op.add_column('users', sa.Column('boss_currency_balance', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'boss_currency_balance')
    op.drop_column('users', 'current_hp')
    op.drop_column('stats', 'is_default')
    op.drop_column('stats', 'combat_role')

    combat_role_enum = postgresql.ENUM('health', 'strength', 'agility', 'focus', 'intellect', name='combatrole')
    combat_role_enum.drop(op.get_bind(), checkfirst=True)

    op.drop_table('bosses')
    op.drop_table('boss_fights')
    # ### end Alembic commands ###
