"""add repeatable and purchase_count to reward

Revision ID: b31ee37e62dc
Revises: 99b56c688326
Create Date: 2026-07-13 12:05:51.413764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b31ee37e62dc'
down_revision: Union[str, Sequence[str], None] = '99b56c688326'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('repeatable', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('rewards', sa.Column('purchase_count', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###
    op.execute("UPDATE rewards SET purchase_count = 1 WHERE is_purchased = true")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'purchase_count')
    op.drop_column('rewards', 'repeatable')
    # ### end Alembic commands ###
