"""add last_completed_at to quest

Revision ID: bf61db68332e
Revises: 28f0cf6fe5ff
Create Date: 2026-07-05 13:38:35.471633

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf61db68332e'
down_revision: Union[str, Sequence[str], None] = '28f0cf6fe5ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('last_completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'last_completed_at')
    # ### end Alembic commands ###
