"""add ondelete behavior to foreign keys

Revision ID: c6058206f258
Revises: 19369be6cca4
Create Date: 2026-07-07 13:55:14.903577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6058206f258'
down_revision: Union[str, Sequence[str], None] = '19369be6cca4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('quests_stat_id_fkey'), 'quests', type_='foreignkey')
    op.drop_constraint(op.f('quests_tag_id_fkey'), 'quests', type_='foreignkey')
    op.drop_constraint(op.f('quests_user_id_fkey'), 'quests', type_='foreignkey')
    op.create_foreign_key(None, 'quests', 'tags', ['tag_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'quests', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'quests', 'stats', ['stat_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(op.f('rewards_user_id_fkey'), 'rewards', type_='foreignkey')
    op.create_foreign_key(None, 'rewards', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('stats_user_id_fkey'), 'stats', type_='foreignkey')
    op.create_foreign_key(None, 'stats', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tags_linked_stat_id_fkey'), 'tags', type_='foreignkey')
    op.drop_constraint(op.f('tags_user_id_fkey'), 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'stats', ['linked_stat_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tags', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('transaction_logs_user_id_fkey'), 'transaction_logs', type_='foreignkey')
    op.create_foreign_key(None, 'transaction_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction_logs', type_='foreignkey')
    op.create_foreign_key(op.f('transaction_logs_user_id_fkey'), 'transaction_logs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key(op.f('tags_user_id_fkey'), 'tags', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('tags_linked_stat_id_fkey'), 'tags', 'stats', ['linked_stat_id'], ['id'])
    op.drop_constraint(None, 'stats', type_='foreignkey')
    op.create_foreign_key(op.f('stats_user_id_fkey'), 'stats', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'rewards', type_='foreignkey')
    op.create_foreign_key(op.f('rewards_user_id_fkey'), 'rewards', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.drop_constraint(None, 'quests', type_='foreignkey')
    op.create_foreign_key(op.f('quests_user_id_fkey'), 'quests', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('quests_tag_id_fkey'), 'quests', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key(op.f('quests_stat_id_fkey'), 'quests', 'stats', ['stat_id'], ['id'])
    # ### end Alembic commands ###
