"""add hp_regen_date and boss_defeated reason

Revision ID: ce94c11f6c14
Revises: ec499e888426
Create Date: 2026-07-09 12:54:08.320272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce94c11f6c14'
down_revision: Union[str, Sequence[str], None] = 'ec499e888426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hp_regen_date', sa.Date(), nullable=True))
    op.execute("ALTER TYPE transactionreason ADD VALUE 'boss_defeated'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hp_regen_date')
    # ### end Alembic commands ###
