"""add active_consumables to boss_fight

Revision ID: dc215cac2917
Revises: a1c4f7b920de
Create Date: 2026-08-10 11:01:20.611306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc215cac2917'
down_revision: Union[str, Sequence[str], None] = 'a1c4f7b920de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'boss_fights',
        sa.Column('active_consumables', sa.JSON(), nullable=False, server_default='[]'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boss_fights', 'active_consumables')
    # ### end Alembic commands ###
