"""add unlock_level to reward

Revision ID: ec499e888426
Revises: 8459fa99761b
Create Date: 2026-07-09 11:26:13.488408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec499e888426'
down_revision: Union[str, Sequence[str], None] = '8459fa99761b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rewards', sa.Column('unlock_level', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rewards', 'unlock_level')
    # ### end Alembic commands ###
