"""add currency and xp awarded to boss fight

Revision ID: ff7d57b9e371
Revises: 462cefb6a222
Create Date: 2026-08-11 18:04:36.424518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff7d57b9e371'
down_revision: Union[str, Sequence[str], None] = '462cefb6a222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boss_fights', sa.Column('currency_awarded', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('boss_fights', sa.Column('xp_awarded', sa.Integer(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boss_fights', 'xp_awarded')
    op.drop_column('boss_fights', 'currency_awarded')
    # ### end Alembic commands ###
